name: Manual Build (快速构建)

on:
  workflow_dispatch:
    inputs:
      platform:
        description: '选择构建平台'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - windows
        - mac

jobs:
  build-windows:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'windows' }}
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        # 移除cache配置避免锁定文件问题
    
    - name: Install dependencies
      run: |
        npm install --no-package-lock
    
    - name: Build Windows app
      run: |
        npm run build-win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/
        retention-days: 7

  build-mac:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'mac' }}
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        # 移除cache配置避免锁定文件问题
    
    - name: Install dependencies
      run: |
        npm install --no-package-lock
    
    - name: Build Mac app
      run: |
        npm run build-mac
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Mac build
      uses: actions/upload-artifact@v4
      with:
        name: mac-build
        path: dist/
        retention-days: 7
